from __future__ import annotations

DEFAULT_ITEM_NAME = "面包"
DEFAULT_LEVEL_BREAD_NUM = 10
DEFAULT_ALLOW_RANDOM_ROB = True
DEFAULT_ALLOW_RANDOM_GIVE = True

DEFAULT_BUY_COOLDOWN_SECONDS = 4200
DEFAULT_MIN_BUY_AMOUNT = 1
DEFAULT_MAX_BUY_AMOUNT = 9
DEFAULT_BUY_GOLDEN_BONUS = 20
DEFAULT_BUY_LOW_STOCK_BONUS = 10
DEFAULT_BUY_LOW_STOCK_THRESHOLD = 10
DEFAULT_BUY_TOO_MANY_THRESHOLD = 90

DEFAULT_EAT_COOLDOWN_SECONDS = 4800
DEFAULT_MIN_EAT_AMOUNT = 2
DEFAULT_MAX_EAT_AMOUNT = 8
DEFAULT_EAT_EXTRA_COOLDOWN_SECONDS = 1800
DEFAULT_EAT_HUNGRY_THRESHOLD = 90

DEFAULT_ROB_COOLDOWN_SECONDS = 5000
DEFAULT_MIN_ROB_AMOUNT = 2
DEFAULT_MAX_ROB_AMOUNT = 7
DEFAULT_ROB_POLICE_EXTRA_COOLDOWN_SECONDS = 2400

DEFAULT_GIVE_COOLDOWN_SECONDS = 3000
DEFAULT_MIN_GIVE_AMOUNT = 1
DEFAULT_MAX_GIVE_AMOUNT = 10

DEFAULT_BET_COOLDOWN_SECONDS = 5400
DEFAULT_MIN_BET_AMOUNT = 5
DEFAULT_MAX_BET_AMOUNT = 10
DEFAULT_BET_POLICE_EXTRA_COOLDOWN_SECONDS = 2400

GESTURE_SCISSORS = "剪刀"
GESTURE_ROCK = "石頭"
GESTURE_PAPER = "布"
ALL_GESTURES = (GESTURE_SCISSORS, GESTURE_ROCK, GESTURE_PAPER)
